-- Generated by Oracle SQL Developer Data Modeler 21.2.0.165.1515
--   at:        2021-11-20 14:18:57 AEDT
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

--DROP TABLE booking CASCADE CONSTRAINTS;
--
--DROP TABLE chat CASCADE CONSTRAINTS;
--
--DROP TABLE educator CASCADE CONSTRAINTS;
--
--DROP TABLE educator_qualification CASCADE CONSTRAINTS;
--
--DROP TABLE feedback CASCADE CONSTRAINTS;
--
--DROP TABLE subjects CASCADE CONSTRAINTS;
--
--DROP TABLE MENTEE CASCADE CONSTRAINTS;
--
--DROP TABLE mentee_post CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE booking (
    booking_id          INTEGER NOT NULL,
    start_date_time     DATE NOT NULL,
    end_date_time       DATE NOT NULL,
    meeting_link        VARCHAR2(500) NOT NULL,
    e_id       INTEGER NOT NULL,
    subject_id INTEGER NOT NULL,
    m_id        INTEGER NOT NULL,
    complete            BLOB NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT booking_pk PRIMARY KEY ( booking_id );

CREATE TABLE chat (
    chat_id       INTEGER NOT NULL,
    text          VARCHAR2(500),
    e_id          INTEGER NOT NULL,
    m_id          INTEGER NOT NULL
);

ALTER TABLE chat ADD CONSTRAINT chat_pk PRIMARY KEY ( chat_id );

CREATE TABLE educator (
    e_id        INTEGER NOT NULL,
    email       VARCHAR2(50) NOT NULL,
    full_name   VARCHAR2(100) NOT NULL,
    description VARCHAR2(1000),
    rating      FLOAT
);

ALTER TABLE educator ADD CONSTRAINT educator_pk PRIMARY KEY ( e_id );

CREATE TABLE educator_qualification (
    qualification VARCHAR2(500) NOT NULL,
    e_id INTEGER NOT NULL
);

CREATE TABLE feedback (
    rating        INTEGER,
    feedback      VARCHAR2(100),
    e_id INTEGER NOT NULL,
    m_id     INTEGER NOT NULL
);

CREATE TABLE subjects (
    subject_id    INTEGER NOT NULL,
    subject_name  VARCHAR2(100) NOT NULL,
    e_id INTEGER NOT NULL
);

ALTER TABLE subjects ADD CONSTRAINT subjects_pk PRIMARY KEY ( subject_id );

CREATE TABLE mentee (
    m_id      INTEGER NOT NULL,
    full_name VARCHAR2(100) NOT NULL,
    mentee_type VARCHAR2(100) NOT NULL,
    country   VARCHAR2(100)
);

ALTER TABLE mentee ADD CONSTRAINT mentee_pk UNIQUE ( m_id );

CREATE TABLE mentee_post (
    post_id         INTEGER NOT NULL,
    description     VARCHAR2(500) NOT NULL,
    role_title      VARCHAR2(50) NOT NULL,
    start_date_time DATE NOT NULL,
    end_date_time   DATE NOT NULL,
    m_id            INTEGER NOT NULL
);

ALTER TABLE mentee_post ADD CONSTRAINT mentee_post_pk PRIMARY KEY ( post_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_educator_fk FOREIGN KEY ( e_id )
        REFERENCES educator ( e_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_subjects_fk FOREIGN KEY ( subject_id )
        REFERENCES subjects ( subject_id );

ALTER TABLE booking
    ADD CONSTRAINT booking_mentee_fk FOREIGN KEY ( m_id )
        REFERENCES mentee ( m_id );

ALTER TABLE chat
    ADD CONSTRAINT chat_educator_fk FOREIGN KEY ( e_id )
        REFERENCES educator ( e_id );

ALTER TABLE chat
    ADD CONSTRAINT chat_mentee_fk FOREIGN KEY ( m_id )
        REFERENCES mentee ( m_id );

ALTER TABLE educator_qualification
    ADD CONSTRAINT qualification FOREIGN KEY ( e_id )
        REFERENCES educator ( e_id );

ALTER TABLE feedback
    ADD CONSTRAINT feedback_educator_fk FOREIGN KEY ( e_id )
        REFERENCES educator ( e_id );

ALTER TABLE feedback
    ADD CONSTRAINT feedback_mentee_fk FOREIGN KEY ( m_id )
        REFERENCES mentee ( m_id );

ALTER TABLE subjects
    ADD CONSTRAINT subjects_educator_fk FOREIGN KEY ( e_id )
        REFERENCES educator ( e_id );

ALTER TABLE mentee_post
    ADD CONSTRAINT mentee_post_mentee_fk FOREIGN KEY ( m_id )
        REFERENCES mentee ( m_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             0
-- ALTER TABLE                             16
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE MENTEE                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
